### ISSUE TITLE
Skrypt sie wysypuje po jakimś czasie

### ISSUE THREAD

**Issue by IDeserveToBeWrited** [szymi-/fronius-to-influx#3]
Od razu zacznę że nie jestem zaawansowanym userem i poprawne uruchomienie skryptu zajęło mi kilka godzin z jakiegoś powodu.
Ale jak już go odpaliłem i działał, no to po jakiejś pół godzinie zauważyłem że nie działa.
Uruchamiam go na rPi3B w screenie podczas startupu.

Ale do szczegółów, w końcu miałem trochę cierpliwości żeby złapać co się dzieje i jest to jak następuje:
```
Data written
Data written
Traceback (most recent call last):
  File "/home/pi/skrypty/fronius-to-influx/src/fronius_to_influx.py", line 130, in run
    collected_data.extend(self.translate_response())
  File "/home/pi/skrypty/fronius-to-influx/src/fronius_to_influx.py", line 54, in translate_response
    'ErrorCode': self.data['Body']['Data']['DeviceStatus']['ErrorCode'],
KeyError: 'DeviceStatus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/prod.py", line 20, in <module>
    z.run()
  File "/home/pi/skrypty/fronius-to-influx/src/fronius_to_influx.py", line 144, in run
    raise WrongFroniusData('Response structure is not healthy')
fronius_to_influx.WrongFroniusData: Response structure is not healthy
```

Niestety moja wiedza jest zbyt mała żeby w ogóle nie bać się próbować szukać co może być przyczyną, ale wystarczająca żeby dodać skrypt do crona, który uruchomi skrypt z powrotem jeśli spadnie z rowerka. Niestety prowadzi to do lekkich dziur w wykresach.
![firefox_2020-12-03_14-01-15](https://user-images.githubusercontent.com/8699007/101021355-20edd980-3570-11eb-8f31-8b0db7b6a511.png)

**Comment by szymi-** [comment]
Miałem podobne problemy jak używałem Mikrotika jako AP. Po przejściu na AP Cisco problem ustąpił.

**Comment by IDeserveToBeWrited** [comment]
Falownik jak i Raspberry są zapięte po kablu i nie mam żadnych Mikrotików ani Cisco w domu.
Udało mi się problem zniwelować restartem procesów co 24h i praktycznie co 5 sekund sprawdzanie czy skrypt nie spadł z rowerka xD
