### ISSUE TITLE
Problem z Pytz?

### ISSUE THREAD

**Issue by mx12mx12** [szymi-/fronius-to-influx#4]
Cześć,
używam od dłuższego czasu Twojego narzędzia. Jest super! Polecałem kilku osobom również. Dzięki!
Od kilku dni coś nie działa, przy uruchomieniu skryptu prod.py mam komunikat:
 Traceback (most recent call last):
  File "/home/pi/fronius-to-influx-master/src/prod.py", line 1, in <module>
    from fronius_to_influx import FroniusToInflux
  File "/home/pi/fronius-to-influx-master/src/fronius_to_influx.py", line 7, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'

Jak próbowałem doinstalować jeszcze raz pytz pojawił się komunikat, że jest już (zgodnie z prawdą) zainstalowany.
W czym może być problem?
Pozdrawiam Michał

**Comment by szymi-** [comment]
Cześć, pewnie coś się zaktualizowało na raspberry do jakiejś niekompatybilnej wersji. Spróbuj odpalić skrypt w virtualenvie (w razie czego tu jest jakaś instrukcja, może się nada: https://raspberrypi-aa.github.io/session4/venv.html). Ja używam pythona w wersji 3.6.8 (taki akurat był w Ubuntu jak to pisałem :) ), w nowszych wersjach nie wiem czy wszystko będzie działać (raczej powinno, ale nie sprawdzałem). Jak stowrzysz sobie virtualenva to wejdź do niego i zainstaluj paczki w wymaganych wersjach (`pip install -r requirements.txt`) i odpalaj skrypt w virtualenvie.
